### ISSUE TITLE
No : at todos

### ISSUE THREAD

**Issue by toger5** [need12648430/godot3-todo#1]
I would prefer if i am not forced to do #TODO :
Or make it a option?

**Comment by toger5** [comment]
change
```todo_regex.compile("(?:#|//)\\s*(" + PoolStringArray(TYPES.keys()).join("|") + ")\\s*:\\s*([^\\n]+)")```
to
```todo_regex.compile("(?:#|//)\\s*(" + PoolStringArray(TYPES.keys()).join("|") + ")\\s*([^\\n]+)")```

**Comment by need12648430** [comment]
Looks like you found a solution. :)

**Comment by toger5** [comment]
Yea ;)
Issue was more about how to handle it. Can there be a setting? To choose if the : is mandatory? Would u create a commit removing the colon from the regex?

**Comment by need12648430** [comment]
I had to tweak some things anyway for 3.1 anyway, so I figured I'd make colons optional while I'm at it. I've updated both TODO and Scene Notes. If you're using Scene Notes, you will lose your notes upon update - they can be retrieved by moving `res://addons/scene_notes/notes.ini` to `res://scene-notes.ini`

I pushed the update to the asset library, but it may take some time for approval. In the meantime, you can download and install the addon manually from this repository.

**Comment by toger5** [comment]
Man this is great news. Thank you!
Why move the ini to res://

**Comment by need12648430** [comment]
It enables symlinking the addon instead of reinstalling it in each project. Eases testing. Willing to change it back if the previous behavior is preferred, or make it an option.
