### ISSUE TITLE
Missing Godot store listing

### ISSUE THREAD

**Issue by Developer626** [need12648430/godot3-todo#2]
When using Godot 3.0.6 and checking the AssetLib, I cannot find the listing to add this add-on.

**Comment by need12648430** [comment]
It works for both 3.0 and 3.1 but I didn't want to spam the asset library. Guess I have to. I'll submit it for 3.0 soon.

**Comment by Developer626** [comment]
Cool. I'm just starting out using Godot, so I haven't learned how to side install add-on yet.

**Comment by need12648430** [comment]
If you mean installing from outside the asset library, you just download it and copy the 'addons' directory into the root of your project. Enable in project settings and you're all set.
